Attempting to add Coloumb Force
Attempting to add coulomb force but keep getting an error:

Traceback (most recent call last):
  File "C:\Users\Zeros\OneDrive\Documents\GitHub\Physics-2.0\Physics 2.0.py", line 191, in <module>
    main()
  File "C:\Users\Zeros\OneDrive\Documents\GitHub\Physics-2.0\Physics 2.0.py", line 183, in main
    refresh_display(settings_window, screen, bodies, camera)
  File "C:\Users\Zeros\OneDrive\Documents\GitHub\Physics-2.0\Physics 2.0.py", line 30, in refresh_display
    pg.draw.circle(screen, b.color, (int(x), int(y)), int(b.radius * cam.scale), 0)
OverflowError: Python int too large to convert to C long